export type ICategory =
  | "Wall"
  | "Floor"
  | "Ceiling"
  | "Roof"
  | "Column"
  | "Door"
  | "Window"
  | "Structure Beam"
  | "Structure Column"
  | "Structure Wall"
  | "Structure Slab"
  | "Structure Foundation"
  | "ReinForcement"
  | "Duct"
  | "Pipe"
  | "AirTerminal";
